import matplotlib.pyplot as plt
def plot_stats(log_data):
    plt.figure(figsize=(12,8))
    plt.subplot(3,2,1)
    plt.plot(log_data['frame'], log_data['speed'], label='Speed')
    plt.title('Geschwindigkeit'); plt.xlabel('Frame'); plt.ylabel('Speed')
    plt.subplot(3,2,2)
    plt.plot(log_data['frame'], log_data['drift'], label='Drift')
    plt.title('Drift'); plt.xlabel('Frame'); plt.ylabel('Drift')
    plt.subplot(3,2,3)
    plt.plot(log_data['frame'], log_data['wheelie'], label='Wheelie')
    plt.title('Wheelie'); plt.xlabel('Frame'); plt.ylabel('Wheelie')
    plt.subplot(3,2,4)
    plt.plot(log_data['frame'], log_data['offroad'], label='Offroad')
    plt.title('Offroad'); plt.xlabel('Frame'); plt.ylabel('Offroad')
    plt.subplot(3,2,5)
    plt.plot(log_data['frame'], log_data['reward'], label='Reward')
    plt.title('Reward pro Frame'); plt.xlabel('Frame'); plt.ylabel('Reward')
    plt.subplot(3,2,6)
    plt.plot(log_data['frame'], log_data['crashes'], label='Crashes')
    plt.title('Abstürze'); plt.xlabel('Frame'); plt.ylabel('Crashes')
    plt.tight_layout()
    plt.show()